apiVersion: v1
kind: Service
metadata:
  name: graphite
  namespace: default
spec:
  ports:
    - name: graphite
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: statsd
  sessionAffinity: None
  type: NodePort
